## 연습문제 8-3
6x6난수 행렬의 QR분해로부터 U라는 직교 행렬을 만든다.
U의 QR 분해를 계산하고 R = I임을 확인한다.

In [8]:
import numpy as np

A = np.random.randn(6,6)
print(A)
U,R = np.linalg.qr(A)
Q,_R = np.linalg.qr(U)

print(np.allclose(_R,np.eye(6))) # True라면 Identity Matrix 가 맞다.

[[-0.64503568 -0.68335246  0.67317197  0.42703644 -0.49973356 -0.39771768]
 [ 0.40757847 -0.47708674 -0.92056678 -0.22990158 -0.1448483  -1.65784017]
 [-1.43172216 -0.01988569  0.7493534  -1.05621003 -0.21631121 -1.30305606]
 [-0.32851217 -1.82250264  3.15701365 -2.20906121 -0.27051228  0.38427174]
 [-0.40260216  0.03533916 -0.67247897  0.3301374  -1.38959674  0.3557868 ]
 [ 2.95929258  1.49871069  0.09871713 -1.31937334 -1.74292467 -0.957724  ]]
True
