# 행 축소와 LU 분해

## 행 축소
행 축소는 방정식을 수작업으로 푸는 방식으로 오랫동안 인정받아 왔기 때문에 전통적인 선형대수학에서 많은 관심을 받는 주제이다.
실제로 데이터 과학자로 일하면서 연립방정식을 손으로 직접 풀일은 없겠지만, LU분해로 직결되기 때문에 행 축소는  유용하다.

행 축소(row reduction)란 행렬의 행에 스칼라 곱셈과 덧셈이라는 두 가지 연산을 반복적으로 적용하는 작업이다.
행 축소는 하나의 연립방정식 내에서 하나의 방정식을 다른 방정식에 더하는것과 동일한 원리를 사용한다.



In [12]:
import sympy as sym
import numpy as np
#sympy 로 행렬 변환
M = np.array([[1,1,4],[-1/2,1,2]])
symMat = sym.Matrix(M)

#RREF
symMat.rref()[0]

Matrix([
[1, 0, 1.33333333333333],
[0, 1, 2.66666666666667]])

## LU 분해
LU 분해에서 LU는 하삼각, 상삼각에서와 같이 아래 위를 의미한다.
즉 행렬을 두 개의 삼각 행렬의 곱으로 분해하는 것이다.

$$ A = LU $$

$$ \[
\begin{bmatrix}
2 & 2 & 4 \\
1 & 0 & 3 \\
2 & 1 & 2
\end{bmatrix}
=
\begin{bmatrix}
1 & 0 & 0 \\
\frac{1}{2} & 1 & 0 \\
1 & 1 & 1
\end{bmatrix}
\begin{bmatrix}
2 & 2 & 4 \\
0 & -1 & 1 \\
0 & 0 & -3
\end{bmatrix}
\] $$

In [13]:
import scipy.linalg # LU in scipy library
A = np.array([[2,2,4],[1,0,3],[2,1,2]])

_,L,U = scipy.linalg.lu(A)
# 각각 출력한다.
print('L: '),print(L)
print('U: '),print(U)

L: 
[[1.  0.  0. ]
 [0.5 1.  0. ]
 [1.  1.  1. ]]
U: 
[[ 2.  2.  4.]
 [ 0. -1.  1.]
 [ 0.  0. -3.]]


(None, None)