# 역행렬(Inverse Matrix)
역행렬 $(A^{-1})$은 주어진 정방행렬 A에 대해 다음 관계를 만족하는 행렬이다.
$$ AA^{-1} = A^{-1}A = I $$
여기서 $I$는 단위행렬(Identity Matrix)이다.

### 역행렬이 존재하는 조건
1. 행렬 A가 정방행렬이어야 한다.
2. 행렬의 행렬식이 0이 아니어야 한다.

In [6]:
import numpy as np
# 2 x 2 행렬 정의
A = np.array([[4,7],[2,6]])

# 역행렬 계산
A_inv = np.linalg.inv(A)

#결과 출력
print("행렬 A : ")
print(A)
print("\n 역행렬 A^-1 : ")
print(A_inv)

print(A @ A_inv)

행렬 A : 
[[4 7]
 [2 6]]

 역행렬 A^-1 : 
[[ 0.6 -0.7]
 [-0.2  0.4]]
[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


## 축소계수 행렬 계산
### 가우스 조던 소거법으로 도출 가능
#### 축소 계수 행렬의 정의
1. 각 행의 첫번째 0이 아닌 원소는 1이어야 한다.
2. 선행 1이 있는 나머지 열의 나머지원소는 모두 0이어야 한다.
3. 선행 1은 위에서 아래로 이동할수록 점점 오른쪽으로 정렬되어야 한다.
4. 0이 아닌 행은 항상 위쪽에 위치해야한다.

In [9]:
import numpy as np
from sympy import Matrix

A = np.array([
    [1,2,-1,3],
    [2,3,1,7],
    [3,1,2,4]
])

A_reduced = Matrix(A).rref()

print(np.array(A_reduced[0]))

[[1 0 0 0]
 [0 1 0 2]
 [0 0 1 1]]


## 왼쪽 역행렬 계산
행렬 A(3x2)일때 열이 2개 -> 열 벡터가 선형 독립이면 왼쪽 역행렬이 존재함.


In [14]:
import numpy as np

A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
# Left Inverse (A_L^-1 = (A^T A)^-1 A^T)
A_left_inv = np.linalg.inv(A.T @ A) @ A.T

print("왼쪽 역행렬 (Left Inverse):")
print(A_left_inv)
print("결과가 단위행렬이 되는지 검증")
print(A_left_inv @ A)


[[1 2]
 [3 4]
 [5 6]]
A.T @ A
[[35 44]
 [44 56]]
왼쪽 역행렬 (Left Inverse):
[[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]
[[1.00000000e+00 1.33226763e-14]
 [2.66453526e-15 1.00000000e+00]]


## 오른쪽 역행렬 계산

In [17]:
B = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B_right_inv = B.T @ np.linalg.inv(B @ B.T)
print("오른쪽 역행렬 (Right Inverse) : ")
print(B_right_inv)
print("결과가 단위행렬이 되는지 검증")
print(B@B_right_inv)

오른쪽 역행렬 (Right Inverse) : 
[[-0.94444444  0.44444444]
 [-0.11111111  0.11111111]
 [ 0.72222222 -0.22222222]]
결과가 단위행렬이 되는지 검증
[[1. 0.]
 [0. 1.]]


In [20]:
import numpy as np

A = np.array([[1, 2], [3, 4], [5, 6]])  # 3x2 행렬
A_pinv = np.linalg.pinv(A)

print("무어-펜로즈 의사역행렬:")
print(A_pinv)
print(A_pinv @ A)

무어-펜로즈 의사역행렬:
[[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]
[[ 1.0000000e+00 -4.4408921e-16]
 [ 0.0000000e+00  1.0000000e+00]]
