# 직교 행렬과 QR 분해
## 1. 직교 행렬
직교행렬은 QR분해, 고윳값 분해, 특잇값 분해등 여러가지 분해에 필수적인 특수 행렬이다.
문자 Q는 종종 직교행렬을 나타내는 데 사용된다. 직교 행렬은 두가지 속성을 가진다.
### 직교열
    - 행렬의 모든 열은 서로 직교한다.
### 단위노름 열
    - 각 열의 노름은 정확히 1이다.
모든 열은 자기 자신과의 내적은 1이지만 다른 열과의 내적은 0이다.

직교행렬 Q는 아래 조건을 만족한다.
$$ Q^T Q = I $$

In [5]:
import numpy as np
Q1 = np.array([[1,-1],[1,1]]) / np.sqrt(2)
Q2 = np.array([[1,2,2],[2,1,-2],[-2,2,-1]]) / 3
print(Q1.T @ Q1)
print(Q1 @ Q1.T)

print(Q2.T @ Q2)
print(Q2 @ Q2.T)


[[1.00000000e+00 2.23711432e-17]
 [2.23711432e-17 1.00000000e+00]]
[[ 1.00000000e+00 -2.23711432e-17]
 [-2.23711432e-17  1.00000000e+00]]
[[1.00000000e+00 2.46716228e-17 1.54197642e-17]
 [2.46716228e-17 1.00000000e+00 1.23358114e-17]
 [1.54197642e-17 1.23358114e-17 1.00000000e+00]]
[[ 1.00000000e+00  2.46716228e-17 -1.54197642e-17]
 [ 2.46716228e-17  1.00000000e+00 -1.23358114e-17]
 [-1.54197642e-17 -1.23358114e-17  1.00000000e+00]]


순수 회전 행렬도 직교행렬이다.

In [25]:
import numpy as np
import matplotlib.pyplot as plt

origin = np.array([[0,0],[0,0]])
theta = np.radians(45)
Q1 = np.array([[np.cos(theta),np.sin(theta)],[-np.sin(theta),np.cos(theta)]])

print(Q1.T @ Q1)

[[1.00000000e+00 4.26642159e-17]
 [4.26642159e-17 1.00000000e+00]]
